all:
	gcc task18.c -o task18
	./task18 file1.txt
	./task18 file2.txt
	./task18 file3.txt
	./task18 file4.sh
	./task18 dir1
	./task18 dir2
	./task18 symlink_to_file1
	./task18 special_device
	./task18 file1.txt file2.txt dir1 symlink_to_file1
	./task18 nonexistent_file

