# Makefile для protected_editor
CC = gcc
CFLAGS = -Wall

all: protected_editor

protected_editor: protected_editor.c
	$(CC) $(CFLAGS) -o protected_editor protected_editor.c

clean:
	rm -f protected_editor

