all: Task_9 Task_10

Task_9: Task_9.o
	gcc Task_9.o -o Task_9
Task_9.o:
	gcc -c Task_9.c -o Task_9.o

Task_10: Task_10.o
	gcc Task_10.o -o Task_10
Task_10.o:
	gcc -c Task_10.c -o Task_10.o

clean: 
	rm Task_9 Task_10 *.o