# Makefile для line_lookup_alarm
CC = gcc
CFLAGS = -Wall

all: line_lookup_alarm

line_lookup_alarm: line_lookup_alarm.c
	$(CC) $(CFLAGS) -o line_lookup_alarm line_lookup_alarm.c

clean:
	rm -f line_lookup_alarm

