# Makefile для line_lookup_mmap
CC = gcc
CFLAGS = -Wall

all: line_lookup_mmap

line_lookup_mmap: line_lookup_mmap.c
	$(CC) $(CFLAGS) -o line_lookup_mmap line_lookup_mmap.c

clean:
	rm -f line_lookup_mmap

